<a href="https://colab.research.google.com/github/greyhound101/multilingial/blob/master/french_predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Mounted at /content/gdrive


In [2]:
pip install sentencepiece 

In [3]:
pip install transformers

In [4]:
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version nightly --apt-packages libomp5 libopenblas-dev

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5116  100  5116    0     0  33880      0 --:--:-- --:--:-- --:--:-- 33880
Updating... This may take around 2 minutes.
Updating TPU runtime to pytorch-nightly ...
Uninstalling torch-1.8.0a0+unknown:
  Successfully uninstalled torch-1.8.0a0+unknown
Uninstalling torchvision-0.9.0a0+e04de77:
  Successfully uninstalled torchvision-0.9.0a0+e04de77
Copying gs://tpu-pytorch/wheels/torch-nightly-cp36-cp36m-linux_x86_64.whl...
- [1 files][123.1 MiB/123.1 MiB]                                                
Operation completed over 1 objects/123.1 MiB.                                    
Copying gs://tpu-pytorch/wheels/torch_xla-nightly-cp36-cp36m-linux_x86_64.whl...
- [1 files][132.0 MiB/132.0 MiB]                                                
Operation completed over 1 objects/132.0 MiB.                                    
Copying g

In [5]:
import gc
import os
import time
import math
import random
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from datetime import date
from transformers import *
from sklearn.metrics import *
from tqdm.notebook import tqdm

import torch
import torch.nn as nn
import torch.utils.data
import torch.nn.functional as F

import numpy as np
from transformers import AutoTokenizer, AutoModel
import torch.nn as nn
from torch import Tensor
from torch.optim import *
from torch.nn.modules.loss import *
from torch.optim.lr_scheduler import * 
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import RandomSampler
import pandas as pd



def regular_encode(texts, tokenizer, maxlen=192):
    enc_di = tokenizer.batch_encode_plus(
        texts, 
        return_token_type_ids=False,
        pad_to_max_length=True,
        max_length=maxlen
    )
    
    return np.array(enc_di['input_ids'])

class Transformer(nn.Module):
    def __init__(self, transformer, num_classes=1):
        """
        Constructor
        
        Arguments:
            model {string} -- Transformer to build the model on. Expects "camembert-base".
            num_classes {int} -- Number of classes (default: {1})
        """
        super().__init__()
        
        self.transformer = transformer

        self.nb_features = self.transformer.pooler.dense.out_features
        # for param in self.transformer.parameters():
        #   param.requires_grad = False
        self.pooler = nn.Sequential(
            nn.Linear(self.nb_features, num_classes), 
            nn.Sigmoid(),
        )


    def forward(self, tokens):
        """
        Usual torch forward function
        
        Arguments:
            tokens {torch tensor} -- Sentence tokens
        
        Returns:
            torch tensor -- Class logits
        """
        hidden_states = self.transformer(
            tokens, attention_mask=(tokens > 0).long()
        )[1]

        # hidden_states = hidden_states[-1][:, 0] # Use the representation of the first token of the last layer

        ft = self.pooler(hidden_states)

        return ft


In [6]:
class bce(nn.Module):
    def __init__(self, weight=None, size_average=True):
        super(bce, self).__init__()

    def forward(self, inputs, targets, smooth=1):
        
        #comment out if your model contains a sigmoid or equivalent activation layer
        
        #flatten label and prediction tensors
        inputs = inputs.view(-1)
        targets = targets.view(-1)
        
        one=(1-targets)*torch.log(1-inputs)
        zero=(targets*torch.log(inputs))
        loss = torch.mean((one+zero)*-1)
        
        return loss
class JigsawDataset:
    """
    Torch dataset for training and validating
    """
    def __init__(self, x,y,is_test):
        super().__init__()
        self.y = y 
        self.is_test=is_test
        self.sentences = x
        

    def __len__(self):
        return self.sentences.shape[0]

    def __getitem__(self, idx):
      len=self.__len__()
      if idx>len:
        idx=idx%len
      if self.is_test==0:
        return torch.tensor(self.sentences[idx]), torch.tensor(self.y[idx]).float()
      else:
        return torch.tensor(self.sentences[idx])


In [36]:
from sklearn.model_selection import train_test_split
from statistics import mean
import torch_xla
from sklearn.preprocessing import *
import torch_xla.debug.metrics as met
import torch_xla.distributed.data_parallel as dp
import torch_xla.distributed.parallel_loader as pl
import torch_xla.utils.utils as xu
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.test.test_utils as test_utils
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import scipy as sp
import gc
import os
import cv2
import zipfile
from pathlib import Path
import random
import argparse
import sys
from statistics import mean
import yaml
from tqdm.notebook import tqdm
import time
import albumentations as A
from sklearn.model_selection import StratifiedKFold
import random
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from typing import Dict
from tempfile import gettempdir
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from torch import nn, optim
from torch.utils.data import DataLoader
from torchvision.models.resnet import resnet50, resnet18, resnet34, resnet101
from tqdm import tqdm
import seaborn as sns
from matplotlib import pyplot as plt

def train_all(train_loader, model, device, optimizer):
    model.train()
    # t = tqdm(train_loader, disable=not xm.is_master_ordinal())
    model.train()
    lss=bce()
    loss1=[]
    for step, (x, y_batch) in enumerate(train_loader): 
            
            # x = x.to(device)
            y_batch = y_batch.to(device)
            y_pred = model(x)
            
            loss = lss(y_pred.view(-1).float(), y_batch.float())
            loss.backward()
            loss1.append(loss.item())
            xm.optimizer_step(optimizer)
            
            model.zero_grad()
    return mean(loss1)

def valid_all(train_loader, model, device):
    # t = tqdm(train_loader, disable=not xm.is_master_ordinal())
    lss=bce()
    loss1=[]
    for step, (x, y_batch) in enumerate(train_loader): 
            
            # x = x.to(device)
            y_batch = y_batch.to(device)
            y_pred = model(x)
            
            loss = lss(y_pred.view(-1).float(), y_batch.float())
            loss1.append(loss.item())
            
    return mean(loss1)

def predict_all(train_loader, model,device,df,batch_size):
    # t = tqdm(train_loader, disable=not xm.is_master_ordinal())
    predict=[]
    for step, (x) in tqdm(enumerate(train_loader),total=df.shape[0]/(batch_size*8)): 
            
            y_pred = model(x.to(device))
            predict.append(y_pred.cpu().detach().numpy())
            
    return predict


def load_data(lang):
    tst=pd.read_csv('/content/gdrive/My Drive/multilingual/test.csv.zip',usecols=['lang','content'])  .loc[tst['lang']==lang].reset_index(drop=True).drop(['lang'],1)
    print(tst.shape)
    return tst.head(1000)


def get_lang(val,tst,lang):
  df=pd.concat([val,tst],0)
  return df.loc[df['lang']==lang].reset_index(drop=True).drop(['id','lang'],1)

def main():
    epochs=1
    seed=42
    batch_size=16
    # Setting seed
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True

    df=load_data('fr')
    tokenizer = AutoTokenizer.from_pretrained("camembert-base")
    x_train = regular_encode(list(df.content.values), tokenizer, maxlen=192)
    



    def run():

        torch.manual_seed(seed)

        device = xm.xla_device()
        model = AutoModel.from_pretrained("camembert-base")
        model=Transformer(model).to(device)
        model.load_state_dict(torch.load( '/content/gdrive/My Drive/french')['state_dict'])

        #Training
        train_dataset = JigsawDataset(x_train,None,1)


        train_sampler = torch.utils.data.distributed.DistributedSampler(
            train_dataset,
            num_replicas=xm.xrt_world_size(),
            rank=xm.get_ordinal(),
            shuffle=False
        )
        train_loader = torch.utils.data.DataLoader(train_dataset,batch_size=batch_size,
            sampler=train_sampler,
            drop_last=False,
            num_workers=2
        )

        

        
        xm.master_print("Training is Starting ...... ")
        predictions=[]
        para_loader = pl.ParallelLoader(train_loader, [device])
        predictions.append(predict_all(para_loader.per_device_loader(device),model,device,df,batch_size))



        np.save('predictions.npy',predictions)
            


    def _mp_fn(rank, flags):
        torch.set_default_tensor_type('torch.FloatTensor')
        run()
        
    FLAGS={}
    xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')

In [ ]:
main()

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py:2143: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
import seaborn as sns
a=np.load('loss.npy',allow_pickle=False)
sns.scatterplot(y=a,x=range(len(a)))

In [20]:

a=np.load('predictions.npy',allow_pickle=True)
# sns.scatterplot(y=a,x=range(len(a)))

In [32]:
ls=[]
for i in range(len(a[0])):
  ls.extend(a[0][i])

In [35]:
[l.tolist()[0] for l in ls]

[0.7122620344161987,
 0.8482557535171509,
 0.19369137287139893,
 0.013957172632217407,
 0.4314044713973999,
 0.05329489707946777,
 0.19901427626609802,
 0.07988181710243225,
 0.9099643230438232,
 0.15789157152175903,
 0.9435878396034241,
 0.6111634373664856,
 0.001579582691192627,
 0.16222810745239258,
 0.18491509556770325,
 0.004019021987915039,
 0.26752936840057373,
 0.11627554893493652,
 0.5616077780723572,
 0.011059761047363281,
 0.29250413179397583,
 0.009790122509002686,
 0.37644943594932556,
 0.1161855161190033,
 0.0013055801391601562,
 0.754936933517456,
 0.0012272894382476807,
 0.6124148368835449,
 0.5651353597640991,
 0.002841353416442871,
 0.02131316065788269,
 0.569208562374115,
 0.8081423044204712,
 0.018386870622634888,
 0.18516382575035095,
 0.002758413553237915,
 0.3635505735874176,
 0.17278647422790527,
 0.002213031053543091,
 0.7095896005630493,
 0.0015847980976104736,
 0.006323575973510742,
 0.03269702196121216,
 0.28914695978164673,
 0.006201565265655518,
 0.9361860

In [33]:
ls

[array([0.71226203], dtype=float32),
 array([0.84825575], dtype=float32),
 array([0.19369137], dtype=float32),
 array([0.01395717], dtype=float32),
 array([0.43140447], dtype=float32),
 array([0.0532949], dtype=float32),
 array([0.19901428], dtype=float32),
 array([0.07988182], dtype=float32),
 array([0.9099643], dtype=float32),
 array([0.15789157], dtype=float32),
 array([0.94358784], dtype=float32),
 array([0.61116344], dtype=float32),
 array([0.00157958], dtype=float32),
 array([0.16222811], dtype=float32),
 array([0.1849151], dtype=float32),
 array([0.00401902], dtype=float32),
 array([0.26752937], dtype=float32),
 array([0.11627555], dtype=float32),
 array([0.5616078], dtype=float32),
 array([0.01105976], dtype=float32),
 array([0.29250413], dtype=float32),
 array([0.00979012], dtype=float32),
 array([0.37644944], dtype=float32),
 array([0.11618552], dtype=float32),
 array([0.00130558], dtype=float32),
 array([0.75493693], dtype=float32),
 array([0.00122729], dtype=float32),
 arra

In [27]:
a[0][0].detach().numpy()

array([[0.71226203],
       [0.84825575],
       [0.19369137],
       [0.01395717],
       [0.43140447],
       [0.0532949 ],
       [0.19901428],
       [0.07988182],
       [0.9099643 ],
       [0.15789157],
       [0.94358784],
       [0.61116344],
       [0.00157958],
       [0.16222811],
       [0.1849151 ],
       [0.00401902]], dtype=float32)